---
- name: Write deployment artefact to workspace
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Resolve workspace path
      ansible.builtin.set_fact:
        workspace_path: "{{ lookup('env', 'GITHUB_WORKSPACE') | default('../', true) }}"

    - name: Create artefacts directory
      ansible.builtin.file:
        path: "{{ workspace_path }}/artefacts"
        state: directory
        mode: '0755'

    - name: Write DEPLOYED_FILE.txt with timestamp
      ansible.builtin.copy:
        dest: "{{ workspace_path }}/artefacts/DEPLOYED_FILE.txt"
        mode: '0644'
        content: |
          Deployed by GitHub Actions via Ansible.
          Timestamp: {{ lookup('pipe', 'date -u +%Y-%m-%dT%H:%M:%SZ') }}
